### ISSUE TITLE
Info messages result in KeyErrors

### ISSUE THREAD

**Issue by kjgd** [nlsdfnbch/btfxwss#100]
Getting the following error:
    File "/home/user/Bots_BitMEX/btfxwss/connection.py", line 407, in _info_handler
    self.log.info(info_message[data['code']])
    KeyError: 20051
    2017-12-11 00:44:23,619 - ERROR - root.btfxwss.connection - Unknown Info code 20051!

I'm pretty sure the fix is to change the dictionary keys from strings to ints: 
https://github.com/nlsdfnbch/btfxwss/blob/c3520e1da3bda89f762f871c6069d37142491f67/btfxwss/connection.py#L390

I am not very familiar with GitHub or I'd submit a pull request...

**Comment by nlsdfnbch** [comment]
Sorry for the late response - I fixed this on the dev branch!
Thanks for reporting this!
