### ISSUE TITLE
Allowing BtfxWss to connect through a proxy

### ISSUE THREAD

**Issue by andressommerhoff** [nlsdfnbch/btfxwss#103]
BtfxWss doesn't allow to connect through a proxy. I issued a pull request [(102)](https://github.com/nlsdfnbch/btfxwss/pull/102) to make Proxy connections possible. 

Code change was simple: just needed to pass the proxy arguments to the run_forever() function of websocket. The parameters are collected by BtfxWss class when initiated. 

Some example of the usage after merging the pull request:

Simple Proxy:
wss = BtfxWss(http_proxy_host="10.9.9.9", http_proxy_port=8888)

Auth Proxy:
wss = BtfxWss(http_proxy_host="10.9.9.9", http_proxy_port=8888,
                        http_proxy_auth=("username","password"))

Looking forward you merge it!

**Comment by nlsdfnbch** [comment]
merged! Thanks!
