### ISSUE TITLE
objects for subscribing to funding channels?

### ISSUE THREAD

**Issue by seravitae** [nlsdfnbch/btfxwss#105]
Hi, sorry if this is the absolute wrong place to put this, but I can't for the life of me seem to see in the code anywhere that any functions were created for subscribing to channels for funding, such as 'fos', 'fcs', 'fls'... 

is this something not yet completed?

Or alternatively can someone help me work out a generic method for this? I'm very new to this and cannot quite understand the identifiers required for such a channel, so i can't figure out how to use the _subscribe() function.

Cheers in advance,
Seb.

**Comment by nlsdfnbch** [comment]
Hey @seravitae,

Using the `rc` version (install this via `pip install --pre btfxwss` or installing the `dev` branch from the github repo), you can find this information after authenticating and grabbing the queue from `BtfxWss.account`
