### ISSUE TITLE
How to test it, i use the Usage  test code

### ISSUE THREAD

**Issue by kintzhao** [nlsdfnbch/btfxwss#106]
```python
yhzhao@X550JD:~/blockChain/btfxwss/tests$ ./mytest.py 
from: can't read /var/mail/btfxwss
./mytest.py: line 7: syntax error near unexpected token `('
./mytest.py: line 7: `log = logging.getLogger(__name__)'



yhzhao@X550JD:~/blockChain/btfxwss/tests$ pip install btfxwss
Requirement already satisfied (use --upgrade to upgrade): btfxwss in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): websocket-client in /usr/local/lib/python2.7/dist-packages (from btfxwss)
Cleaning up...
yhzhao@X550JD:~/blockChain/btfxwss/tests$ python
Python 3.6.0 (default, Jan 13 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by nlsdfnbch** [comment]
You have a syntax error in your code. Could you post it ? Running the code from the `README.md` works for me without issues.

**Comment by kintzhao** [comment]
yhzhao@X550JD:~/blockChain/btfxwss/tests$ ls
client_tests.py  logging  mytest.py  sys  test.py  time  unittest
yhzhao@X550JD:~/blockChain/btfxwss/tests$ chmod 777 test.py 
yhzhao@X550JD:~/blockChain/btfxwss/tests$ ./test.py 
from: can't read /var/mail/btfxwss
./test.py: line 7: syntax error near unexpected token `('
./test.py: line 7: `log = logging.getLogger(__name__)'

`import logging
import time
import sys

from btfxwss import BtfxWss
    
log = logging.getLogger(__name__)

fh = logging.FileHandler('test.log')
fh.setLevel(logging.DEBUG)
sh = logging.StreamHandler(sys.stdout)
sh.setLevel(logging.DEBUG)

log.addHandler(sh)
log.addHandler(fh)
logging.basicConfig(level=logging.DEBUG, handlers=[fh, sh])
    

wss = BtfxWss()
wss.start()

while not wss.conn.connected.is_set():
    time.sleep(1)

# Subscribe to some channels
wss.subscribe_to_ticker('BTCUSD')
wss.subscribe_to_order_book('BTCUSD')

# Do something else
t = time.time()
while time.time() - t < 10:
    pass

# Accessing data stored in BtfxWss:
ticker_q = wss.tickers('BTCUSD')  # returns a Queue object for the pair.
while not ticker_q.empty():
    print(ticker_q.get())

# Unsubscribing from channels:
wss.unsubscribe_from_ticker('BTCUSD')
wss.unsubscribe_from_order_book('BTCUSD')

# Shutting down the client:
wss.stop()`

**Comment by kintzhao** [comment]
I installed  btfxwss  by pip3. 

kint@ubuntu:~/blockCoin/btfxwss/tests$ python test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from btfxwss import BtfxWss
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/__init__.py", line 1, in <module>
    from btfxwss.client import BtfxWss
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/client.py", line 6, in <module>
    from btfxwss.connection import WebSocketConnection
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/connection.py", line 470
    self.send(**q, auth=True)
                 ^
SyntaxError: invalid syntax

**Comment by nlsdfnbch** [comment]
This library requires python 3.5 or later. Earlier versions won't work.
