### ISSUE TITLE
Invalid syntax (btfxwss 1.1.16)

### ISSUE THREAD

**Issue by crackedit** [nlsdfnbch/btfxwss#107]
Importing BtfxWss causes a SyntaxError:

`from btfxwss import BtfxWss`

`Traceback (most recent call last):
  File "BitfinexWS.py", line 1, in <module>
    from btfxwss import BtfxWss
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/__init__.py", line 1, in <module>
    from btfxwss.client import BtfxWss
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/client.py", line 6, in <module>
    from btfxwss.connection import WebSocketConnection
  File "/usr/local/lib/python3.4/dist-packages/btfxwss/connection.py", line 470
    self.send(**q, auth=True)
                 ^
SyntaxError: invalid syntax`

**Comment by JunaidAthar** [comment]
I had the same issue when I was using Python2.7. Did you make sure you're using Python3?

**Comment by crackedit** [comment]
> I had the same issue when I was using Python2.7. Did you make sure you're using Python3?

I sure am using Python 3.4.

**Comment by nlsdfnbch** [comment]
All my libraries only support python 3.5+ - if you'd be willing to volunteer time and make it compatible with earlier 3.x versions, I will gladly merge your PR!
