### ISSUE TITLE
automatic restart when no heartbeat?

### ISSUE THREAD

**Issue by Serpens66** [nlsdfnbch/btfxwss#15]
After few minutes I get the message:
WARNING:__main__:BtfxWss.heartbeats: Channel ('book', {'freq': 'F0', 'prec': 'P0', 'pair': 'BTCUSD', 'symbol': 'tBTCUSD'}) hasn't sent a heartbeat in 10.06259298324585 seconds!

And the orderbook does not update anymore.

Maybe implement an automate restart?

And can you imagine why I get this error? I started it two times, but both times after ~5 minutes I got no heartbeat anymore.

All I do is waiting and print best bid and best ask from time to time. I want to test for few hours, if orderbook is still consistent. Maybe I need to send a ping from time to time?

PS:
I commented out the two conflicting parts (python 3.4), but since they do not affect orderbook, everything should still work I guess.

edit:
I tried it now with sending a ping every 1 minute.
But according to logfile, after few minutes the "TimeoutError: Ping Command timed out!"
And then I also got no heartbeat anymore... hmm..

If it is relevant:
I did not install this module. I copied the classes.py and exception.py in two new python files, adjusted the exception import and added your example code:

if __name__ == "__main__":
    
    import sys
    import traceback
    
    logging.basicConfig(level=logging.INFO, filename='bitfinex_ws.log')
    log = logging.getLogger(__name__)

    fh = logging.FileHandler('bitfinex_ws.log')
    fh.setLevel(logging.INFO)
    log.addHandler(fh)
    
    wss = BtfxWss(key='my_api_key', secret='my_api_secret')
    wss.start()
    time.sleep(1)  # give the client some prep time to set itself up.
    
    # Subscribe to some channels
    wss.order_book('BTCUSD')
    
    # Send a ping - if this returns silently, everything's fine.
    wss.ping()
    

    count = 0
    while True:
        time.sleep(2)
        bid = wss.books['BTCUSD'].bids[0]
        ask = wss.books['BTCUSD'].asks[0]
        if bid[0] > ask[0]:
            print("BID > ASK")
        count += 1
        if count>30:
            print("bid: {} ... ask: {}".format(bid,ask))
            wss.ping()
            count = 0
    wss.stop()

**Comment by nlsdfnbch** [comment]
Thanks for reporting this!

I have actually fixed this, but it wasn't committed it yet - the thing is, I'm not entirely sure where this originates from and currently it may happen that the API bans you (since you're only allowed 6 requests per minutes, i.e. 6 connection attempts). Since I didn't want people getting temporarily banned because of my code I havent added this fix. 

Rest assured I'm looking into this though!

**Comment by nlsdfnbch** [comment]
I've pushed version 1.0 - it's quite different from the existing code and layout, but if you'd like to can see if the problem remains - It's 3.5+ though

**Comment by ntom** [comment]
Hey Nils thanks for pushing this though i just found this library im going to explore it and have a play over the next few days, looks good
