### ISSUE TITLE
SUBSCRIPTION TO DATA

### ISSUE THREAD

**Issue by prateekdataman** [nlsdfnbch/btfxwss#156]
Inside code you have subscribe to data for trades,tickers and order book, etc. but to get those data from exchange you have implement while loop which is not suitable as well as not working fine as if a user subscribe to market data then they will have to get those data in a variable automatically when there is any activity in exchange....please help me to resolve that

**Comment by deepbrook** [comment]
Sorry, I can't help you with any code implementation that may be specific to your needs.
