### ISSUE TITLE
New websocket-client release breaking code

### ISSUE THREAD

**Issue by niladell** [nlsdfnbch/btfxwss#158]
Hi 

I came back to this library after a while, but a piece of code I have that used to work now was giving me this error.

```
ERROR:websocket:error from callback <bound method WebSocketConnection._on_open of <WebSocketConnection(Thread-28, started daemon 139747911972608)>>: _on_open() missing 1 required positional argument: 'ws'
ERROR:websocket:error from callback <bound method WebSocketConnection._on_message of <WebSocketConnection(Thread-28, started daemon 139747911972608)>>: _on_message() missing 1 required positional argument: 'message'
```

I bypassed it by setting my websocket version to 0.48, as the new released version is what seems to be the issue.

**Comment by deepbrook** [comment]
Hey @niladell,
I'm aware of the breaking change - it's due to the `_on_*` callbacks no longer requiring the `ws` argument. If you have the time, do you think you could submit a PR to fix this ?

It's a small change, but I'm currently swamped with work.
