### ISSUE TITLE
wss.candles(pair, timeframe) adds timeframe to key...

### ISSUE THREAD

**Issue by rjarbour** [nlsdfnbch/btfxwss#16]
`wss.subscribe_to_candles('BTCUSD', '1m')`
leads to 
`defaultdict(<class 'queue.Queue'>, {('candles', 'BTCUSD'): <queue.Queue object at 0x000002749A73E208>})`
calling 
`wss.candles('BTCUSD', '1m')` 
leads to a key of 
`('candles', 'BTCUSD', '1m')`
which does not match the queue's key...

**Comment by nlsdfnbch** [comment]
Hello!
What parameters did you use to subscribe to `candles` ? Could you provide a minimal code example to reproduce this issue?

Have a look at the [CONTRIBUTING.md](https://github.com/nlsdfnbch/btfxwss/blob/master/CONTRIBUTING.MD) to make it easier for us to fix issues.

Thanks for your contribution!
