### ISSUE TITLE
fail to run client.py ,help 

### ISSUE THREAD

**Issue by kilometer2162** [nlsdfnbch/btfxwss#165]
I ran the file 'client.py' ,got this error " Cannot call subscribe_to_ticker() on unestablished connection! "

**Comment by deepbrook** [comment]
Hey @liudy2162 ,
That error speaks for itself - you've tried to subscribe to a ticket before the client was able to establish a connection. Try `time.sleep()` or a `try/except` block to re-try subscibing.

**Comment by kilometer2162** [comment]
Thanks @nlsdfnbch
