### ISSUE TITLE
Authenticated channels? (specifically trade)

### ISSUE THREAD

**Issue by jonathanworkshard** [nlsdfnbch/btfxwss#17]
First off, thank you so much for creating such an amazing and useful program - This has been enormously useful and an amazing resource.

I see that you noted that authenticated channels are a work in progress - what stage of development are they currently and is it possible to place orders with the current code?

**Comment by nlsdfnbch** [comment]
There you go :)

They're on the `dev` branch for now, since I wasn't able to test them yet - but feel free to give them a try!

**Comment by ntom** [comment]
Thanks nils i'll check the dev branch
