### ISSUE TITLE
I try to create new order but nothing happens

### ISSUE THREAD

**Issue by toert** [nlsdfnbch/btfxwss#22]
I run this code:  

> socket = BtfxWss(key, secret)
> socket.start()
> time.sleep(1)
> socket.authenticate()
> order = {
>             "cid": 12345,
>             "type": "MARKET",
>             "symbol": "tBTCUSD",
>             "amount": "1.0",
>             "hidden": 0
>           }
> socket.new_order(**order)
> socket.stop()

And the order isn't created. How can I create new order using btfxwss?

**Comment by nlsdfnbch** [comment]
Hey @toert!
Thanks for submitting this issue.

Your code looks fine. Sorry that it doesn't run as it should :( But no worries, I'll have a look!

I need a few more details to help you out with this issue:

 1. Can you confirm that authentication works? Are there any errors raised or logged?
 2. Confirm that you are receiving data on the other authenticated channels (as a reference, check [this file](https://github.com/nlsdfnbch/btfxwss/blob/master/btfxwss/client.py), starting at line 58, to see what private channels you can try polling). If all are empty, there may be something wrong with the authentication. 
 3. Could you run the above code with debugging enabled and attach the log file? You just have to add the following lines and it should work:

```
import logging
logging.basicConfig(filename="btfxwss.log", level=logging.DEBUG)

socket=BtfxWss(key, secret, log_level=logging.DEBUG)
...
```

Thanks for your patience!

**Comment by toert** [comment]
Actually my CEO said that I have to make a script faster and I deleted all my strings of code and start using v1 directly(without libraries, just requests). However I have logged all requests with your library and it's attached.

> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> ERROR:btfxwss.client:Cannot call authenticate() on unestablished connection!
> ERROR:btfxwss.client:Cannot call new_order() on unestablished connection!
> INFO:btfxwss.connection:Connection Error - [Errno 9] Bad file descriptor
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> INFO:btfxwss.connection:Connection opened
> INFO:btfxwss.connection:Connection closed
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v1/order/new HTTP/1.1" 400 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v1/order/new HTTP/1.1" 400 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v1/order/new HTTP/1.1" 400 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v1/order/new HTTP/1.1" 400 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
> DEBUG:urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v2/auth/r/orders HTTP/1.1" 200 None
>

**Comment by nlsdfnbch** [comment]
You're supposed to use the REST API to make things faster? That's an odd thing to say, but alright - good luck with your efforts :)

This appears like you're either calling `start` and `stop` alot, or the connection times out. Also, all calls to `order/new/` appear to have invalid request parameters (`Status 400` is a `BAD REQUEST`). So I will need more information about how you call the API, and what parameters you're using. 

Can you confirm this is the log from running the code from above once?

**Comment by nlsdfnbch** [comment]
No Response after 11 days, closing..

**Comment by alexeykarnachev** [comment]
I had the same issue. It was fixed by adding sleep for 3 seconds after authentication =)
