### ISSUE TITLE
Nonce small

### ISSUE THREAD

**Issue by alexeykarnachev** [nlsdfnbch/btfxwss#26]
Hi
After wss.authenticate() I got the following traceback:

DEBUG:btfxwss.connection:_on_message(): Received new message {"event":"auth","status":"FAILED","chanId":0,"code":10114,"msg":"nonce: small"} at 1503428552.745091
DEBUG:btfxwss.connection:_system_handler(): Received a system message: {'chanId': 0, 'msg': 'nonce: small', 'event': 'auth', 'code': 10114, 'status': 'FAILED'}
DEBUG:btfxwss.connection:_system_handler(): Distributing {'chanId': 0, 'msg': 'nonce: small', 'code': 10114, 'status': 'FAILED'} to _response_handler..
DEBUG:btfxwss.connection:_response_handler(): Passing {'chanId': 0, 'msg': 'nonce: small', 'code': 10114, 'status': 'FAILED'} to client..
DEBUG:btfxwss.connection:_start_timers(): Resetting timers..
DEBUG:btfxwss.connection:_stop_timers(): Timers stopped.
ERROR:btfxwss.queue_processor:Dtype 'auth' does not have a response handler!

After changing the 'nonce = str(int(time.time() * 1000))' to 'nonce = str(int(time.time() * 1000000))' in client.py (line 467) all works fine

**Comment by nlsdfnbch** [comment]
That's odd - were you able to reproduce this issue constantly, or sporadically? I've never had an issue with it before. 
Thanks for reporting!

**Comment by alexeykarnachev** [comment]
It's a time to time behavior. Now I've changed back the multiplier to 1000 and it works. I think the problem was on the client side. Maybe I've sent more than one requests with the same nonce, but it's strange

**Comment by nlsdfnbch** [comment]
It may be indeed that you sent out several requests within one second,  since the nonce converts the timestamp to an integer first. This could only be avoided by some form of queuing for request calls. I'll have a look at it.

**Comment by nlsdfnbch** [comment]
I just added your fix from above. I don't know why I didn't before, adding a queue for request calls is utter nonesense 😃 , That's what happens when you try to work in vacation mode.
