### ISSUE TITLE
Multi threading

### ISSUE THREAD

**Issue by alexeykarnachev** [nlsdfnbch/btfxwss#27]
Hi,
I'm newbie in multi threading and I want to achieve the behavior of the parallel channels processing in one class (with common fields). But when I use the common BtfxWss in different threads I get the following:

File "c:\python35\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\python35\Lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python35\Lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\python35\Lib\multiprocessing\popen_spawn_win32.py", line 66, in init
    reduction.dump(process_obj, to_child)
  File "c:\python35\Lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

So, sorry for so stupid question, but is this correct to use the same BtfxWss object in different processes or should I create new instance for each process?
Most likely I do not fully understand how multithreading works, but let me start with this question

**Comment by nlsdfnbch** [comment]
Let's see if I understand you correctly:
You'd like to process the data that arrives in the btfxwss class in a parallel way, meaning simultaneously, correct? 
In that case you'll only need a single btfxwss class. Then,  start a Process (from the multiprocessing module) and give it a function that pulls data from the btfxwss properties and processes it.

**Comment by alexeykarnachev** [comment]
Yes, you are right, that is exactly what i want.

I've tried the following:

import time
from multiprocessing import Process
from btfxwss import BtfxWss

key = 'abc'
secret = 'abc'
pair = 'BCHUSD'


def process_order_book(raw_books):
    while True:
        raw_orders = raw_books.get()
        print(raw_orders)


if __name__ == '__main__':
    wss = BtfxWss(key=key, secret=secret, log_level='DEBUG')
    wss.start()
    time.sleep(2)
    wss.authenticate()
    time.sleep(2)
    wss.subscribe_to_raw_order_book(pair=pair, prec='R0', len='100')
    time.sleep(2)

    raw_books = wss.raw_books(pair=pair)

    p1 = Process(target=process_order_book, kwargs={'raw_books': raw_books})
    p1.start()
    p1.join()


As you can see, I just print the raw books in new process. It works, but it prints only few first orders (messages from queue) and then it stucks on raw_books.get(). What am I doing wrong?

**Comment by alexeykarnachev** [comment]
UPD:

Ok, I got it.
After using multithreading, but NOT multiprocessing all works fine.
I think it's because of that the BtfxWss (and its properties) are not so easy serialazable and Python can not share objects between processes. But threads have the same memory space, that's why threads work:

```python
import time
import threading
from btfxwss import BtfxWss

key = 'abs',
secret = 'abs'
pair = 'BCHUSD'


def process_order_book(raw_books):

    while True:
        raw_orders = raw_books.get()
        print(raw_orders)

threads = []
if __name__ == '__main__':

    wss = BtfxWss(key=key, secret=secret, log_level='DEBUG')
    wss.start()
    time.sleep(2)
    wss.authenticate()
    time.sleep(2)
    wss.subscribe_to_raw_order_book(pair=pair, prec='R0', len='100')
    time.sleep(2)

    raw_books = wss.raw_books(pair=pair)

    t = threading.Thread(target=process_order_book, args=(raw_books,))
    threads.append(t)
    t.start()
```

**Comment by nlsdfnbch** [comment]
Well, the issue with using the `threading` module is that it doesn't actually process data in a parallel manner. 
I could make use of `multiprocessing.Queue` instead of `queue.Queue` in a future release, that way you can pass the `Queue` object accessed via the properties to truly parallel processes. Otherwise, I'm not convinced you'd gain much from using threading in this context. 
But do let me know your findings!

**Comment by alexeykarnachev** [comment]
I've spent some time yesterday to understand the difference between processes and threads and yes, you are right, it'll be not so much odds using a threads.
And I think, multiprocessing queues will be a really great feature =)
