### ISSUE TITLE
Auth handler

### ISSUE THREAD

**Issue by alexeykarnachev** [nlsdfnbch/btfxwss#28]
Hi
It looks like QueueProcessor has no auth handler, is it so? And does it mean, that currently I can not obtain auth data: my open orders, wallet and so on?

**Comment by nlsdfnbch** [comment]
Not quite - the handler for data which is received after authenticating is handled by the `_handle_account()` method, but this was indeed not yet called in the main routine of the queue processor. I've added it now - however, I cannot currently test it, since Im on vacation. 
Perhaps you could confirm it does ?

**Comment by alexeykarnachev** [comment]
Yes, sure I can test it. 
How can I achieve this? Should you commit version with _handle_account() in main queue processor routine and then I'll test it? Or should I add this handling by myself?

**Comment by alexeykarnachev** [comment]
Ok, what I've realized at this moment:

1. 
_handle_account(self, dtype, data, ts) method has dtype argument, but in main queue processor routine it is called only with two arguments. dtype actually is not using now, so for my debug purposes I just removed this argument from method

2. 
some channels need to be added into self.account_channel_names dict.
For example, when I want to receive my new orders ('on' channel which is not presented yet in account_channel_names) I faced with this Exception
{KeyError}: 'on' 
at self.account_channel_names[data[0]] (270 line in queue_processor.py)

If I understood your code and idea correctly, new account_channel_name should be added, for example:
self.account_channel_names = {....
                                                    'on': 'Order New'}
and then new property should be added to the client:
    @property
    def new_orders(self):
        """
        :return: Queue()
        """
        return self.queue_processor.account['Order New']

something like this. Am I right?

**Comment by nlsdfnbch** [comment]
Yes, that's spot on. 
And removing the `dtype` parameter is the way to go - it's not needed, and thus should have been removed by me anyway. 
Don't forget to submit a pull request if you've managed to fix it! 
Appreciate the help!

**Comment by alexeykarnachev** [comment]
Hi
Just tried to do a pull request in dev branch, but it's failed with error code 403:

Push failed: unable to access 'https://github.com/nlsdfnbch/btfxwss.git/': The requested URL returned error: 403

I'm trying to do it within Pycharm. What am I doing wrong?

**Comment by jcranney** [comment]
pull request #30 seems to have fixed it. Cheers @alexeykarnachev
