### ISSUE TITLE
Queue or LifoQueue

### ISSUE THREAD

**Issue by ArthurJ** [nlsdfnbch/btfxwss#32]
It would be nice to have a LifoQueue ticker to get always the most recent information.

**Comment by alexeykarnachev** [comment]
Such approach would cause the memory error because you need to do something with the rest part of messages in queue (not only with the last one)

**Comment by ArthurJ** [comment]
Yeah, that's what I did. The loop is not a problem.
`[ticker_q.get() for _ in range(ticker_q.qsize())][-1]`

The fixed size is necessary indeed, this implementation seems to be useful to client programmers that need the N most recent tickers.

**Comment by nlsdfnbch** [comment]
I have thought about a `LIFO` queue as well, however, at this point the library is intentionally rather bare bones. It would technically be no problem to implement this yourself - simply call `get()` on the Queue and fill it into a `deque` which then allows you to keep a history of the past X ticks of ticker data.

**Comment by nlsdfnbch** [comment]
With the introduction of `zmq` in the next release and the deprecation of the current client interface, this issue is no longer relevant.
