### ISSUE TITLE
Re-Subscribe to channels after Connection Time-Out

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/btfxwss#33]
As pointed out by @8ick in #29:

> I may have a related problem, when trying to establish a long-running websocket connection. I'm not sure if it is intentional or not, but at the moment it seems that the client does not resubscribe to the same channels it was connected to before a timeout or disconnect happened. No subscribed channel leads to endless reconnects due to timeouts. Is this behavior intended or do you consider an automatic renewal of subscriptions?

This should be handled properly.

**Comment by nlsdfnbch** [comment]
@8ick, I've added a handler for this on dev - would you be willing to give a test spin? I found some time afterall to implement it.

**Comment by 8ick** [comment]
@nlsdfnbch, gave it a try, unfortunately on reconnect it seems to get stuck in an endless loop, sending subscriptions forever:

```
DEBUG  : 2017-08-29 15:51:31,197 websocket       - [trace] - send: b'\x81\xbf\x8a|d!\xf1^\x01W\xef\x12\x10\x03\xb0\\FR\xff\x1e\x17B\xf8\x15\x06D\xa8PD\x03\xe9\x14\x05O\xe4\x19\x08\x03\xb0\\FU\xe3\x1f\x0fD\xf8^H\x01\xa8\x0f\x1dL\xe8\x13\x08\x03\xb0\\FD\xfe\x14\x06U\xe9^\x19'
DEBUG  : 2017-08-29 15:51:31,197 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbfu\x92R\x0e\x0e\xb07x\x10\xfc&,O\xb2p}\x00\xf0!m\x07\xfb0kW\xber,\x16\xfa3`\x1b\xf7>,O\xb2pz\x1c\xf19k\x07\xb0~.W\xe1+c\x17\xfd>,O\xb2pk\x01\xfa0z\x16\xb0/'
DEBUG  : 2017-08-29 15:51:31,198 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbf\x9d\xda\\n\xe6\xf89\x18\xf8\xb4(L\xa7\xfa~\x1d\xe8\xb8/\r\xef\xb3>\x0b\xbf\xf6|L\xfe\xb2=\x00\xf3\xbf0L\xa7\xfa~\x1a\xf4\xb97\x0b\xef\xf8pN\xbf\xa9%\x03\xff\xb50L\xa7\xfa~\x0b\xe9\xb2>\x1a\xfe\xf8!'
DEBUG  : 2017-08-29 15:51:31,198 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbf\x1e\xb6\xb0be\x94\xd5\x14{\xd8\xc4@$\x96\x92\x11k\xd4\xc3\x01l\xdf\xd2\x07<\x9a\x90@}\xde\xd1\x0cp\xd3\xdc@$\x96\x92\x16w\xd5\xdb\x07l\x94\x9cB<\xc5\xc9\x0f|\xd9\xdc@$\x96\x92\x07j\xde\xd2\x16}\x94\xcd'
DEBUG  : 2017-08-29 15:51:31,198 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbf\x1c\xbf\xaa?g\x9d\xcfIy\xd1\xde\x1d&\x9f\x88Li\xdd\xd9\\n\xd6\xc8Z>\x93\x8a\x1d\x7f\xd7\xcbQr\xda\xc6\x1d&\x9f\x88Ku\xdc\xc1Zn\x9d\x86\x1f>\xcc\xd3R~\xd0\xc6\x1d&\x9f\x88Zh\xd7\xc8K\x7f\x9d\xd7'
DEBUG  : 2017-08-29 15:51:31,198 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbf\xbc3.\x08\xc7\x11K~\xd9]Z*\x86\x13\x0c{\xc9Q]k\xceZLm\x9e\x1f\x0e*\xdf[Of\xd2VB*\x86\x13\x0c|\xd5PEm\xce\x11\x02(\x9e@We\xde\\B*\x86\x13\x0cm\xc8[L|\xdf\x11S'
DEBUG  : 2017-08-29 15:51:31,198 btfxwss.connection - [send] - send(): Sending payload to API: {"event": "subscribe", "channel": "ticker", "symbol": "ethbtc"}
DEBUG  : 2017-08-29 15:51:31,198 websocket       - [trace] - send: b'\x81\xbf\x0eAM\x85uc(\xf3k/9\xa74ao\xf6{#>\xe6|(/\xe0,mm\xa7m),\xeb`$!\xa74ao\xf1g"&\xe0|ca\xa5,24\xe8l.!\xa74ao\xe0z)/\xf1mc0'
```

**Comment by nlsdfnbch** [comment]
Ah, yes. I see the issue. I've patched it. Unfortunately I still cant test it from this end (vacation and all), so perhaps give this another try?
Thank you for your help!

**Comment by nlsdfnbch** [comment]
Great! Thanks for testing this so quickly.

**Comment by rafaelcapucho** [comment]
Hello @nlsdfnbch .

Sorry to reopen this, I did it just to send you a message, instead of open a new issue.

I just would like to suggest you to release a new version on `pip` with all devs changes. There are many important bugfixes like this one that make a big difference :)

I have a bot running and I often face the connection problem, but it seems to be working well with the changes from `dev`.

Again, thank you so much for your time and creativity, you rocks!
Be free to close it again, cya.

**Comment by nlsdfnbch** [comment]
Hey @rafaelcapucho! 
Next time,  do not hesitate to open a new issue for this - they're free of charge and help me stay organised ;) 
I have a release planned for the coming weeks,  but I'm currently not able to make time to deploy it to pypi. But rest assured, a release is coming!

**Comment by rafaelcapucho** [comment]
Hi again @nlsdfnbch :)

Just because I said it was ok, I saw a bad behavior, my logs says it stopped with a `Connection closed`, as:

```
INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'BTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'IOTUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'ETHUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'LTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.connection:Connection closed
```

And it didn't connect automatically again, as you can see it created a big gap in my chat until I restart the process:
![gap](https://user-images.githubusercontent.com/163367/30399857-72e8fa22-98ab-11e7-97b9-2549d5ea9f2d.png)

Looking at the logs, I don't see an Exception, are there any way where I could catch and reconnect issue a new reconnection? or any other solution? thx!!

**Comment by rafaelcapucho** [comment]
Locally it seems to be working, since I was not sure that the production one had the `dev` version, I updated to give another try, lets see :)

```
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
INFO:btfxwss.connection:_on_open(): Connection reconnected, re-subscribing..
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
```

**Comment by nlsdfnbch** [comment]
@rafaelcapucho , that last log looks good to me - can you confirm this works? Let me know if the problem persists (but please open a new issue for it this time ;) )

cheers,
Nils
