### ISSUE TITLE
Sleep time after `start` affects behaviour

### ISSUE THREAD

**Issue by Leobouloc** [nlsdfnbch/btfxwss#4]
I tried the sample code in the README.  My issue is with the effect of setting sleep time in this line: 

```
time.sleep(1)  # give the client some prep time to set itself up.
```

When keeping `1` second sleep time, I could receive server responses. When I then set sleep time to `5`, values in wss.tickers and wss.books would no longer update no matter how long I waited:

```
print(wss.tickers['BTCUSD'])
print(wss.books['BTCUSD'].bids())  # prints all current bids for the BTCUSD order book
print(wss.books['BTCUSD'].asks())  # prints all current asks for the BTCUSD order book
[]
[]
[]
```
This behaviour seems like it should not be expected. 

Also, NB: there is a `'` missing in `print(wss.tickers['BTCUSD])`) in the README.

Thank you for sharing your code.

**Comment by nlsdfnbch** [comment]
I'll take a look at this at the weekend - it is indeed unexpected behaviour. Thanks for submitting this!
