### ISSUE TITLE
Once connection is broken it won't reconnect

### ISSUE THREAD

**Issue by ntom** [nlsdfnbch/btfxwss#42]
Hi, 

I have this issue where by once a connection is broken (Restarted Bitfinex end or cloudflare error or something)... the connection is closed.. it trys reconnecting.. over and over again.. endlessly.. but never does.... just waits 10 seconds then connection closed then retrys.. over and over.... 

IF I kill the script then restart it it reconnects fine and works up until the next time it dies for some reason then again unable to restart...  
   
Because the script doesn't actually die... just endlessly tries to reconnect.. I can't really run a bash script to check if its still running all the time.. 
  
Are you familiar with this issue ?

**Comment by nlsdfnbch** [comment]
Hey @ntom!

This issue is due to the fact that the client doesn't resubscribe after a connection breaks. This issue should be fixed in `dev`. Could you verify you're using the master branch?

**Comment by ntom** [comment]
I am using the dev branch but i will update to the newest version now and see how it goes. Thanks. Great library btw. I looked into coding my own, found yours, then dissected it to see if it was any good and got half way through and thought 'shit this thing is perfect, so good' - lol

**Comment by ntom** [comment]
Okay I just pulled the latest dev branch, i'll close this ticket now and maybe add in comments to #33 if i have the issue again. Thanks for the fast response.
