### ISSUE TITLE
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

### ISSUE THREAD

**Issue by ntom** [nlsdfnbch/btfxwss#44]
After updating to the latest dev branch, after about 2 days of running i got this error... 

```
Exception in thread Thread-3091435:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/apache2/htdocs/Bots/btfxwss/connection.py", line 232, in send_ping
    self.socket.send(json.dumps({'event': 'ping'}))
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by ntom** [comment]
I just rerun and not long after i got this again...

```
Exception in thread Thread-7185:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/apache2/htdocs/Bots/btfxwss/connection.py", line 232, in send_ping
    self.socket.send(json.dumps({'event': 'ping'}))
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

I think it would be better if after it gets these errors the script actually dies... because otherwise u check if its running and its still running, its just dead inside.. where as if the script actually exited and died properly.. you could at least be notified about its death...

**Comment by ntom** [comment]
Failed another 2 times in the last hour again...

**Comment by nlsdfnbch** [comment]
This is now handled and logged. Killing it entirely shouldn't be necessary. The websocket app reconnects automatically and does do so pretty reliably.

**Comment by ntom** [comment]
Thanks, will repull now

**Comment by ntom** [comment]
You pushed this onto master or dev ? I repulled dev and it just happened again. ..

**Comment by ntom** [comment]
Reason for death 

```
Exception in thread Thread-6602:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/apache2/htdocs/Bots/btfxwss/connection.py", line 232, in send_ping
    self.socket.send(json.dumps({'event': 'ping'}))
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

```

**Comment by ntom** [comment]
fml if i know how to send you a pull request...

**Comment by ntom** [comment]
Okay So i just got the error come up:  
  
`2017-09-10 13:09:04,497 -- ERROR -- connection 235 -- send(): Did not send ping - client not connected.`  
  
This is cool, but the script still continues to hang at this point and do nothing from here on in...

**Comment by ntom** [comment]
Trying a little:  
  
```
        except websocket.WebSocketConnectionClosedException:
            self.log.error("send(): Did not send out ping - client not connected. ")
            self.disconnect()
            self.reconnect()
```

will keep here updated. 
I did try just 'reconnect()' but it didn't do anything so now put in the disconnect first.. try and make sure stuff is cleared maybe...

**Comment by nlsdfnbch** [comment]
That's odd. :/ hm.
When you say it "hangs", is that reflected in the logs? So is there literally nothing happening after that or is it stuck in a reconnect loop?

Could you post the logs so I can have a look?

**Comment by ntom** [comment]
"hangs" as in, once it posts the above message... that's it... doesn't to do anything, i can't repaste the message right now because i just restarted it, maybe take some time before it does it again... but it basically reads like...  
`
..getting data....
..getting data...
 2017-09-10 14:06:10,348 -- ERROR -- connection 235 -- send(): Did not send out ping - client not connected.
`  
and thats it.. it stops right there.. no more messages.. no attempts.. just nothing..

**Comment by ntom** [comment]
See picture of how the script looks... - https://imgur.com/a/jm0XZ  
IT is literally just hanging like that not forever basically.. 
  
I tell you what did work for me though, sticking the "_connect()" function underneath it - but something is clearly wrong because it disconnects and reconnects every 5-10mins.

**Comment by ntom** [comment]
It''s been a few days and i'm going to close this issue... 
Incase anyone else has this problem, i solved it by just adding the _connect() function after the ping fails..  
  
```
        try:
            self.socket.send(json.dumps({'event': 'ping'}))
        except websocket.WebSocketConnectionClosedException:
            self.log.error("send(): Did not send out ping - client not connected. ")
            self._connect()
```

**Comment by nlsdfnbch** [comment]
Hey @ntom  ,
Please don't close issues to which I don't respond immediately - I work on this project in my free time and don't always have the time to provide a fix as soon as an issue is opened (although I try to). Closing this issue only removes it from my to do list,  but since this obviously persists, it shouldn't be closed. 
Thanks again for reporting! If possible, provide a log file of your fixed implementation - the behaviour is odd and calling connect opens a new instance of the connection object,  which shouldn't be necessary.

**Comment by ntom** [comment]
Hey @nlsdfnbch,  
I only closed it because i thought maybe it was some local issue since no one else is experiencing it....   
  
What do you mean by,  "If possible, provide a log file of your fixed implementation"  ?  
  
There is no log to report back on, as soon as the connection dies with ""send(): Did not send out ping - client not connected. "" .. then it just reconnects..  as per my code i stuck in there..  
  
```
    def send_ping(self):
        """Sends a ping message to the API and starts pong timers.

        :return:
        """
        self.log.debug("send_ping(): Sending ping to API..")
        try:
            self.socket.send(json.dumps({'event': 'ping'}))
        except websocket.WebSocketConnectionClosedException:
            self.log.error("send(): Did not send out ping - client not connected. ")
            self._connect()
        self.pong_timer = Timer(self.pong_timeout, self._check_pong)
        self.pong_timer.start()
```

**Comment by nlsdfnbch** [comment]
lol, well you're not entirely wrong - but not because it's ugly, but because it doesn't truly fix the issue (whatever it may be). 

It may be possible that it is a local problem, but as long as we're not sure, let's treat this as a short-coming of my programming skills, until proven otherwise ;) 

I hope to find time this weekend to stress test the client myself and see if I can get this behaviour logged.

**Comment by nlsdfnbch** [comment]
I lost track of this, but I haven't had this issue - does this still persist on the release branch for you, @ntom ?

**Comment by nlsdfnbch** [comment]
Closing, since no response for over a month.
