### ISSUE TITLE
Test for initial connection state should be inside BtfxWss.start()

### ISSUE THREAD

**Issue by fredbeltrao** [nlsdfnbch/btfxwss#46]
This snippet of code at Usage section in README.md

```
while not wss.conn.connected.is_set():
    time.sleep(1)
```

Should be inside BtfxWss.start():

```
    def start(self):
        """Start the client.
        
        :return: 
        """
        self.conn.start()
        self.queue_processor.start()
        while not self.conn.connected.is_set():
            time.sleep(.1)
```
This would avoid end user to care about this.

**Comment by nlsdfnbch** [comment]
This is taken care of by the client already- calling a a subscribe method on an unestablished connection causes the `@is_connected` decorator to issue an Error log.  That way the client doesn't freeze the application if no connection can be established.
