### ISSUE TITLE
error code 10100 (auth: invalid)

### ISSUE THREAD

**Issue by lucasjota** [nlsdfnbch/btfxwss#49]
Hello!,

When receiving this error, connection keeps working but only for unauthenticated channels.
Patched it like this:
```
=== modified file 'connection.py'
--- connection.py       2017-09-18 00:47:35 +0000
+++ connection.py       2017-09-18 01:55:39 +0000
@@ -47,6 +47,7 @@
 
         # Connection Handling Attributes
         self.connected = Event()
+        self.needsreauth = Event()
         self.disconnect_called = Event()
         self.reconnect_required = Event()
         self.reconnect_interval = reconnect_interval if reconnect_interval else 10
@@ -389,6 +390,7 @@
         """
         errors = {10000: 'Unknown event',
                   10001: 'Unknown pair',
+                  10100: 'Auth invalid',
                   10300: 'Subscription Failed (generic)',
                   10301: 'Already Subscribed',
                   10302: 'Unknown channel',
@@ -401,6 +403,8 @@
             # Unknown error code, log it and reconnect.
             self.log.error("Received unknown error Code in message %s! "
                            "Reconnecting..", data)
+        if data['code'] == 10100:
+            self.needsreauth.set()
 
     def _data_handler(self, data, ts):
         """Handles data messages by passing them up to the client.

```
So it is possible to check and solve from `BtfxWss` instance if wanted/necessary:
```
if self.conn.needsreauth.is_set():
  self.authenticate()
```
After reconnect, all keeps smooth again.

Best Regards,

**Comment by alexeykarnachev** [comment]
Hello!
nlsdfnbch, I need this bug-fix asap =)
Could you please advice me the best way from your point of view to fix it. I'll try to make the patch yesterday.

**Comment by nlsdfnbch** [comment]
Thanks @alexeykarnachev! I'm working on it already,  tho. It should be deployed in the next few hours.  The thing is, we need to move the authentication to the connection class,  because we'd have to otherwise hold a reference to the client in connection, which just isn't very nice to look at. If you have a better suggestion,  don't hesitate to share!

**Comment by nlsdfnbch** [comment]
It's not as pretty as I'd like - the whole way the resubscription is being handles could be better, but the above commit should fix the issue nonetheless. 

I / we should perhaps look into a better way to implement this. Could you verify this is working now @lucasjota , @alexeykarnachev ? Use the `dev` branch, as the fix isnt on prod yet.

**Comment by alexeykarnachev** [comment]
Cool. I'll check it in next hour, but I need a way to simulate an authintification lost. Any ideas?

**Comment by nlsdfnbch** [comment]
..authenticate with the api, pull the ethernet cable and reconnect it again? :'D That'd be easiest I can think of for an interrupted connection. I think that would work.

**Comment by alexeykarnachev** [comment]
Just tried it:
Got the following message
ERROR:btfxwss.connection:Received unknown error Code in message {'code': 10100, 'msg': 'auth: invalid'}! Reconnecting..
Unfortunately it's hard to obtain logs. I switched them off, because there is tremendous amount of them (raw books, trades and so on)

**Comment by alexeykarnachev** [comment]
Oh, ok =) It's because there is no such code in codes dict

**Comment by nlsdfnbch** [comment]
Yes, that's because I'm a nugget and forgot them. fixed that.

**Comment by alexeykarnachev** [comment]
Tried it again,
Re-auth still does not work =)

**Comment by alexeykarnachev** [comment]
Here is another thing which looks like a bug:

connection.py (262:266)

            auth_sig = hmac.new(self.secret.encode(), auth_string.encode(),
                                hashlib.sha384).hexdigest()

            payload = {'event': 'auth', 'apiKey': self.key, 'authSig': auth_sig,
                       'authPayload': auth_string, 'authNonce': nonce}

self.key and self.secret does not exist. Maybe, ".self" should be removed ?

**Comment by nlsdfnbch** [comment]
of course they should be. I don't know what's going on with me today. You make a great debugger, tho ;D

**Comment by nlsdfnbch** [comment]
looking back, probably wouldve been faster if you had implemented it - I'm coding with my ass today. Fixed that!

**Comment by alexeykarnachev** [comment]
Ok, sure.
Actually it looks like it was the last fix.
Just tried and I think it works. Anyway, if I'll find any bugs, I'll make pull request.
thx!
