### ISSUE TITLE
Lack of state of authentication and reconnection

### ISSUE THREAD

**Issue by carsonip** [nlsdfnbch/btfxwss#52]
The current library lacks the state of authentication. It is still fine until the library reconnects to bitfinex without letting the rest of the code know. Is there any way to notify the other side of the program to re-issue authentication? Maybe a queue containing reconnection signals?

I am happy to implement it and make a PR if you are not available to do so. Let's agree on a way to achieve this if there isn't an existing way. Many thanks!

**Comment by nlsdfnbch** [comment]
Hey @carsonip !
Thanks for contributing! 
Issue #49 already reported this,  and the current dev branch should already have fixed this.  Feel free to confirm this is handled (and of course to report if it isn't). 
Thanks!

**Comment by carsonip** [comment]
That's great. I'll get back to you after I test it.
