### ISSUE TITLE
wrong plus/minus sign of volume

### ISSUE THREAD

**Issue by teresa256** [nlsdfnbch/btfxwss#53]
Sometime plus/minus sign of volume on trades method response data is wrong.

Evidence:
In this case, -4 should be +4.
(['te', [69742359, 1506137906000, -0.24, 3613.6]], 1506137906.7423086)
(['te', [69742360, 1506137906000, -0.00762595, 3613.5]], 1506137906.8536527)
(['tu', [69742359, 1506137906000, -0.24, 3613.6]], 1506137906.8545558)
(['tu', [69742360, 1506137906000, -0.00762595, 3613.5]], 1506137906.8882198)
(['te', [69742367, 1506137916000, -4, 3615.6]], 1506137916.9646268) <--- this volume should be +4
(['tu', [69742367, 1506137916000, -4, 3615.6]], 1506137916.9763083) <--- this volume should be +4

snapshot on https://cryptowat.ch/bitfinex/btcusd/1m at the same time:
![evidence](https://user-images.githubusercontent.com/32213186/30769946-257a3934-a05f-11e7-8b03-d96d3d627fc8.png)

**Comment by nlsdfnbch** [comment]
Hey @teresa256, 
Thanks for contributing! 
I'm pretty sure that I do not modify the data, but instead hand it out as is. 
If that's true (I'll double check it tomorrow,  or perhaps you or @alexeykarnachev has time to verify this?) then this would be something you'd have to report to crypto watch / bitfinex directly as it's not btfxwss messing up the sizes.

**Comment by nlsdfnbch** [comment]
I've look at the code and I indeed do not do any editing of data.
This leads me to the conclusion that this is semantics-related. 
Afterall, a sell trade always has an equal opposing buy trade. The data you receive is the raw feed from bitfinex, hence this is an issue you'd have to discuss further with crypto watch. 
Thanks for taking the time to contribute to the project tho! If you have further inquiries, don't hesitate to open another issue!
