### ISSUE TITLE
Example Usage Errors in README.md

### ISSUE THREAD

**Issue by alexfowler** [nlsdfnbch/btfxwss#54]
When trying to run the provided code in the example, the following line of code seems to cause issues:

`wss.conn.wait():`

If I try to run the code in it's origina form I get **SyntaxError: invalid syntax**. 

If I remove the ' : ', I get **AttributeError: 'WebSocketConnection' object has no attribute 'wait**

When I comment it out, I get the following stack trace error:
_**Traceback (most recent call last):
  File "C:/Users/Nietzsche/Google Drive/Project Cryptic/bitfinex_test.py", line 33, in <module>
    ticker_q = wss.tickers('BTCUSD')  # returns a Queue object for the pair.
  File "C:\Users\Nietzsche\Google Drive\Project Cryptic\py_venv\crypticpy\lib\site-packages\btfxwss\client.py", line 228, in tickers
    raise KeyError(pair)
KeyError: 'BTCUSD'**_

**Comment by nlsdfnbch** [comment]
Hey @alexfowler  !
Thanks for contributing. 
The issue you mention is fixed on the dev branch,  and will be fixed in the next release. 
Cheers! 
Nils
