### ISSUE TITLE
Spell Check all the things!

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/btfxwss#57]
There's likely a boat full of spelling errors and grammatical atrocities in the code - log messages, doc strings and comments all need to be reviewed. 

Feel free to contribute!

**Comment by schamp** [comment]
I can do this.

**Comment by nlsdfnbch** [comment]
@schamp , cool. cool cool cool.
One thing: make sure you do this on the release branch!
cheers,
Nils
