### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by apotapov** [nlsdfnbch/btfxwss#63]
Any plans to support Python 2? Specifically 2.7.

Upgrading to Python 3 is not something that we can currently do with our system.

Thanks

**Comment by apotapov** [comment]
Tried to run 3to2 on it but, the unit tests are failing with:
```
$ python tests/client_tests.py
test_is_connected_decorator_works_as_expected (__main__.BtfxWssTests) ... ok
test_subscribing_to_data_works (__main__.BtfxWssTests) ... ERROR

======================================================================
ERROR: test_subscribing_to_data_works (__main__.BtfxWssTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/client_tests.py", line 28, in test_subscribing_to_data_works
    wss.tickers(u'BTCUSD').get(block=False)
  File "/Users/user/.virtualenvs/btfxwss/lib/python2.7/site-packages/btfxwss/client.py", line 228, in tickers
    raise KeyError(pair)
KeyError: u'BTCUSD'
```

I'm going to play around with using web sockets directly.

**Comment by apotapov** [comment]
Also fixed the issue with KeyError.

If for whatever reason this doesn't get merged and deployed. You can modify your `requirements.txt` to replace:
`btfxwss==1.1.1`
with
`-e git://github.com/TapWealth/btfxwss.git#egg=btfxwss`

**Comment by nlsdfnbch** [comment]
Hey @apotapov!
thanks for the PR and the issue!
As I have pointed out in the PR, I will not merge it since I do not believe in supporting Python2 development at this point, since it's just a little over 2 years left before it is officially not supported anymore.
Thank you again for your efforts!
