### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by pchandra-uchicago** [nlsdfnbch/btfxwss#67]
Hi,
I am not able to get updates of order book. I am subscribing to a channel using wss.subscribe_to_order_book('BTCUSD'). Shouldn't i keep getting orderbook updates till I unsubscribe the channel.

Thanks

**Comment by nlsdfnbch** [comment]
Hey @pchandra-uchicago!

Thanks for submitting an issue. You are correct - once you subscribe to the API you should receive data as long as you're subscribed and the connection doesn't drop.

Could you run the code again and supply the log files? That way I can look into this matter.

Cheers,
Nils

**Comment by pchandra-uchicago** [comment]
Thanks for the instant response Nils.  Below is code snippet I am running

# Subscribe to some channels
wss.subscribe_to_order_book('BTCUSD')

**# Do something else
t = time.time()
while time.time() - t < 5:
    pass**

count =0
while True:
    order_q = wss.books('LTCUSD')
    rowCnt = 0
    while not order_q.empty():
        print(order_q.get())
        rowCnt += 1
    print("Round " + str(count) + " size " + str(rowCnt))
    count += 1
    time.sleep(5)

I have two questions here. 
1. After the first run, subsequent run is just an update to the order book. Am i right about that ?
2. If I remove the section in bold, I throws me a Keyerror(pair). Are you doing that for a reason ?

Great work though !

Cheers
Prakash

**Comment by pchandra-uchicago** [comment]
Sorry missed adding log messages. Below is what is logged

INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'book', 'symbol': 'LTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('book', 'LTCUSD')
INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'book', 'symbol': 'LTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('book', 'LTCUSD')

**Comment by nlsdfnbch** [comment]
1. After you subscribe, the client sets up a queue for all order book data related to your pair - as soon as it gets confirmation of the subscription from the bitfinex server. You can then access this `Queue()` to read out the data the client received.  The client does not return a single orderbook view, but raw data from which you must build the order book yourself. As you can [read in the documentation](https://docs.bitfinex.com/v1/reference#ws-public-order-books), the first message will be a snapshot, and subsequent messages will be updates to that snapshot - you must apply these changes yourself. `btfxwss` does not do this for you.

2. That's because the client needs time to process the subscription- hence you should keep that loop so it can set itself up and your subscriptions are properly processed. Otherwise, you will receive a `KeyError` (as you have observed) - indicating that there has been no data received for that pair yet.

**Comment by pchandra-uchicago** [comment]
Thanks Nils. That was helpful and sorry for the delayed response.

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago , no problem! Glad I was of help!

**Comment by pchandra-uchicago** [comment]
I have an other query..The orderbook updates is causing my order book to grow in size. Any suggestions on how to deal with this issue ?

Thanks
Prakash

**Comment by nlsdfnbch** [comment]
Hey @pchandra-uchicago ,
you can find an answer to your question in the [bitfinex docs](https://bitfinex.readme.io/v2/reference#ws-public-order-books):

> when count = 0 then you have to delete the price level.
4.1 if amount = 1 then remove from bids
4.2 if amount = -1 then remove from asks

So check the `count` parameter and `dict.pop()` the price level from your order book. You can avoid errors when attempting to `pop` a price which you previously hadn't added by wrapping it in a `try/except` block:
```python
try:
    your_book.pop(price_level)
except KeyError:
    pass
```

**Comment by pchandra-uchicago** [comment]
Hi Nils, thanks for the link. I am now able to handle the order book size. However, what I am noticing is that if i keep updating my order book, at some point the bids become greater than the offer or vice versa. I have attached order book logs..As you can see at one point, the best bid is 5939.4 and ask is 5937.8. The bids and offers before the  dotted line in the log file is correct. After the dotted line, its incorrect.
Bids are in descending order and asks in ascending order. My guess this occurs when there is a price jump and for some reason, 5939.4 isn't pushed out. What do you think

Thanks
Prakash
[output.log](https://github.com/nlsdfnbch/btfxwss/files/1419183/output.log)

**Comment by pchandra-uchicago** [comment]
Hi Nils. I again observed the above mentioned issue where the bid > offer at some point and it remains that way.  I have attached another output log. Please take a look
[output.log](https://github.com/nlsdfnbch/btfxwss/files/1422905/output.log)

**Comment by nlsdfnbch** [comment]
Hey @pchandra-uchicago,
sorry for the radio silence, I came down with the flu and wasn't able to respond quicker.

Have a look here:
https://bitfinex.readme.io/v2/docs/ws-general#section-configuration

You can enable message sequencing to make sure you the client hasn't missed anything. As for the problem itself, this isn't an issue with `btfxwss` per se - messages do get lost, so every now and then the order book will be invalid. In this case, it is easiest to reconnect to the API, by stopping and starting the client. 
For now there is no `restart()` method, to make it easier to simply reset the connection to the API - but I will open an issue for this feature to be implemented.

Cheers,

Nils

**Comment by pchandra-uchicago** [comment]
Hey Nils, Thanks for prompt reply. Hope you are feeling better now. 

I saw the implementation by @runz0rd. Thanks @@runz0rd.
 Is this change part of pip now. Because I upgraded the package, but I don't see the changes yet.

I have an other query. Is there a sample code that shows how to place a new order ?

Cheers
Prakash

**Comment by pchandra-uchicago** [comment]
Hey Nils,

I have two questions.
1.  I am providing the api key and secret to btfxwss.  I see authenticate(self) definition in client, But I am not sure if its used to authenticate.  How can i vet that its logged in using the credentials I pass?

2.  I was trying to place a test order using new_order((self, **order_settings). I passed order_settings as below
order_settings= {'cid': 01256098,
                     'type': "EXCHANGE LIMIT",
                     'symbol': self.currencypair,
                     'amount': str(1),
                     'hidden': 0,
                     'price': str(6000)}
This doesn't seem to work. Can you shed some light on this please

**Comment by nlsdfnbch** [comment]
Hey @pchandra-uchicago ,
Please open a new issue for new questions - otherwise this gets quite unorganised quickly. Please always include a complete code snippet,  properly formatted in github markdown, as well as logs (see the readme example on setting up logging). 

For 1.), make sure you leave time for the client to connect by adding a wait call (see example in the readme)
