### ISSUE TITLE
def authenticate() calls key= instead of api_key=

### ISSUE THREAD

**Issue by thedudeBTC** [nlsdfnbch/btfxwss#72]
in client.py, line 489: self.conn.send(**key**=self.key, secret=self.secret, auth=True)

should be: self.conn.send(**api_key**=self.key, secret=self.secret, auth=True)

The send() function in connection.py has argument "api_key" and not "key"

**Comment by nlsdfnbch** [comment]
Hey @thedudeBTC !
Thanks for submitting this issue - It's fixed with #73 and uploaded to pypi!
Cheers!

Nils
