### ISSUE TITLE
Implement restart/reset methods in client

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/btfxwss#74]
Currently, there is no option to reset the client, in order to simply reconnect to the API - this means, the user must call `stop()` and `start()` on the client object, and then manually resubscribe to previously subscribed channels. 

A `restart()` / `reset()` method should take care of this. Subscriptions are already stored on the `Connection` object, hence this should be simple to implement.

This feature is specifically useful, if the order book is invalid (#67).

**Comment by runz0rd** [comment]
Mind if I take this one?

**Comment by nlsdfnbch** [comment]
@runz0rd, not at all! I'm still sick in bed and shouldn't even be on here - the wife has practically banned me from programming for a few days :'(
;D Thanks!

**Comment by pchandra-uchicago** [comment]
Hey Nils, @runz0rd,

I tried resetting the connection by calling reset() method when I find the order book is invalid. However I get the following error message

'send() argument after ** must be a mapping, not tuple'.  Am I missing something here.

Thanks
Prakash

**Comment by runz0rd** [comment]
@pchandra-uchicago @nlsdfnbch 
This is probably due to the self.channel_configs's (OrderedDict) __iter__.
We can solve this by storing the "q"s somewhere else as well, or add another method to the OrderedDict in order to extract the map instead of a tuple.

**Comment by pchandra-uchicago** [comment]
Hi @runz0rd ,

I tried passing a dict instead of OrderedDict to send(). This doesn't solve the issue though. Could you please take a look.

Thanks
Prakash

**Comment by pchandra-uchicago** [comment]
Any takers ?

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago, this should now be working correctly.

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - Is it on pypi or production ?

**Comment by nlsdfnbch** [comment]
It's on pypi,  integrated into the latest stable release(or "production") and the prerelease. If it isn't working  don't forget the logs!

**Comment by pchandra-uchicago** [comment]
Thanks Nils. So i can do a pip install as I am more comfortable with that than pypi. Will keep you posted on this

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - reset works fine. Is there any way to speed up the subscription of order book. It takes sometime to open the connection, authenticate and then subscribe for the connection. The reason I am asking is the order book becomes invalid quite often and stopping and turning all channels back up takes time. Please let me know.

Slightly off topic - how can I check the execution status of my limit orders/market orders?

Thanks
Prakash

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago, there is no faster way I know of.

Regarding the state, you're notified via the account channel about fills, partial fills and order executions. If you want to query a state (send a request) you will have to do so via REST.

Closing this, as the issue is resolved.

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - Thanks for the inputs.

I have two more questions regarding status. Let me know if you want me to create a new thread

1.  Can you have a Websocket working along with REST ? Its a silly question, but just wanted to confirm
2. When the new order is sent, how can we get to know if the order was submitted successfully ?

Thanks
Prakash

**Comment by nlsdfnbch** [comment]
1. Theoretically yes- but bitfinex doesn't sequence their websocket and REST messages globally, hence there will always be room for inaccuracies. No global sequencing means that you cannot guarantee a REST repsonse being before or after a websocket message and vice versa.

2. Again, the confirmation can be read out via the account channel. Check out the bitfinex docs - they explain what type of message is received is sent as a response to a new order.

**Comment by pchandra-uchicago** [comment]
Regarding the 2nd question,

I read the API docs and when I subscribe to trades, I can see the 'te' followed by 'tu' messages. But I am not sure how to subscribe to an account channel. I don't see a subscribe_account_channel function that does the job.

**Comment by nlsdfnbch** [comment]
The account channel is automatically subscribed to when you authenticate with the API - 'te' and 'tu' messages, for example, are on that channel; so you have already accessed this channel.

**Comment by pchandra-uchicago** [comment]
This means that one can receive 'te' and 'tu' messages specific to the trades pertaining to an account?  If that's the case, then I can keep waiting for these messages to see if my trade went through.

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - could you please guide me a bit on how to get trades pertaining to my account. 

I have the below code. subscribe_to_trades('LTCUSD') is probably giving me the list of all trades for LTCUSD pair.  I have attached the logs below
[test.log](https://github.com/nlsdfnbch/btfxwss/files/1467411/test.log)


`c = BtfxWss(key=key, secret=secret, log_level=logging.DEBUG)
c.start()
while not c.conn.connected.is_set():
    time.sleep(1)

c.authenticate()
time.sleep(2)

c.subscribe_to_trades('LTCUSD')
 #Do something else
t = time.time()
while time.time() - t < 5:
    pass
trades = c.trades('LTCUSD')
while True:
    while not trades.empty():
        print(trades.get())`

Thanks
Prakash

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - slightly off topic. when I send new orders can't i send a payload like below

`c = BtfxWss(key=key, secret=secret, log_level=logging.DEBUG)
c.start()
while not c.conn.connected.is_set():
    time.sleep(1)
c.authenticate()
payload= {"cid": 12345, "type": "EXCHANGE LIMIT", "symbol": "tLTCUSD", "amount": '1.0', "price": '60.0',
                  "hidden": 0}
c.new_order(payload)` 

Sending  payload to new_order this way throws TypeError: new_order() takes 1 positional argument but 2 were given.   Could you please advice

Thanks

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago this is off topic indeed - please open new issues for unrelated questions.

In your case, you're missing the dictionary unpacking using starred expressions, as keyword arguments must be passed, not a single positional.

```python
c.new_order(**payload)
```

**Comment by pchandra-uchicago** [comment]
@nlsdfnbch  - Apologies..I will keep that in mind.

Thanks for the timely response

Cheers
Prakash

**Comment by pchandra-uchicago** [comment]
Hi Nils,

I am receiving 'te' and 'tu' messages when i subscribe to trades. But I am not able to identify which of these trade messages pertain to my order. Could you please help me with that.

Thanks

**Comment by nlsdfnbch** [comment]
@pchandra-uchicago ,
as usual, it is just a matter of reading the documentation for [new orders ](https://bitfinex.readme.io/v2/reference#ws-input-order-new)and the [orders messages](https://bitfinex.readme.io/v2/reference#ws-auth-orders). All of the `te` and `tu` are exclusive to your account's orders. Hence, you simply need to look for your order's ID in the [trade messages](https://bitfinex.readme.io/v2/reference#ws-auth-trades).
