### ISSUE TITLE
Authentication error in master branch

### ISSUE THREAD

**Issue by eSanity** [nlsdfnbch/btfxwss#76]
Issue #61 has been fixed for the dev branch, but could it be added to main branch as well? I am using the main branch and authentication failed with the exact same errors from Issue #61

**Comment by nlsdfnbch** [comment]
I'll push a beta version this noon, you should then be able to install it via pip using `pip install --pre btfxwss` - I'll let you know once this is done!

**Comment by nlsdfnbch** [comment]
uploaded to pypi, @eSanity !
