### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by pchandra-uchicago** [nlsdfnbch/btfxwss#77]
Hi Nils,

I am getting TypeError when I  try to authenticate. Below is the code snippet and along with the logs

```python
from btfxwss import BtfxWss
log = logging.getLogger(__name__)
fh = logging.FileHandler('test.log')
fh.setLevel(logging.DEBUG)
sh = logging.StreamHandler(sys.stdout)
sh.setLevel(logging.DEBUG)
log.addHandler(sh)
log.addHandler(fh)
logging.basicConfig(level=logging.DEBUG, handlers=[fh, sh])

wss = BtfxWss(key="abcd", secret="abcde")
wss.start()
while not wss.conn.connected.is_set():
    time.sleep(1)
wss.authenticate()
```

[test.log](https://github.com/nlsdfnbch/btfxwss/files/1434365/test.log)

**Comment by pchandra-uchicago** [comment]
Hi Nils,

Now worries. It was my fault to ask all questions on a thread.
I installed a pre-release version. Now I am getting below error

ERROR:btfxwss.queue_processor:Dtype 'auth' does not have a response handler!

Have attached the logs

Thanks
Prakash
[test.log](https://github.com/nlsdfnbch/btfxwss/files/1434553/test.log)

**Comment by nlsdfnbch** [comment]
Alright, good to know - there is an identical issue (#78) about this, I'll post update on there and close this down to avoid duplicates.

**Comment by pchandra-uchicago** [comment]
Thanks Nils

Prakash
