### ISSUE TITLE
Auth reconnection issue

### ISSUE THREAD

**Issue by Changsung** [nlsdfnbch/btfxwss#85]
Hello @nlsdfnbch 

I have a reconnection issue for authentication in the current release version and there might be something to fix. 

When the socket acts on reconnection and resubscription, the payload of channel configs is popped and sent it through the socket for subscription and added back to q_list in case of a re-occurrence of resubscription. But for the authentication channel, after it pops from the channel configs, it isn't added back to q_list because of 'continue' in the while loop. So I think that when the reconnection occurs again, the authenticated channel wouldn't be resubscribed. 

In my opinion, `q_list.append((identifier, q.copy()))` shold be located after `sidentifier, q = self.channel_configs.popitem(last=True if soft else False)` and remove the below `append`.

https://github.com/nlsdfnbch/btfxwss/blob/423afb678341d7b7e00cbade0314d61a5c4a116d/btfxwss/connection.py#L455

Thank you.

**Comment by nlsdfnbch** [comment]
Hey @Changsung  ,
Thanks for submitting this (and the PR). Much appreciated! 

It's merged and will be up on pypi later today. 

Thanks! 

Nils

**Comment by nlsdfnbch** [comment]
Uploaded to pypi! Closing this issue.
