### ISSUE TITLE
Order failure

### ISSUE THREAD

**Issue by Michshelle** [nlsdfnbch/btfxwss#89]
Hello team,

I tried to create new_order via the api but always ended up by returning a False orders.empty() and a blank item of orders.get().   I'm not sure whether it is my code issue or the api.  Can you help to guide me a bit here?  Many thanks.

Basically, I just gather the pieces together.  Only I inserted my own API and input a random number for 'cid' in dict 'Morder'.   The auth part is fine and no error message shown after it got run.   Below is the snippet.

Python36, MacOSX 10.13.1
```
import logging,time,sys
from btfxwss import BtfxWss

log = logging.getLogger(__name__)

fh = logging.FileHandler('test.log')
fh.setLevel(logging.DEBUG)
sh = logging.StreamHandler(sys.stdout)
sh.setLevel(logging.DEBUG)
 
log.addHandler(sh)
log.addHandler(fh)
logging.basicConfig(level=logging.DEBUG, handlers=[fh, sh])
 
wss = BtfxWss(key = "nJz",secret="wObSTc")
wss.start()
while not wss.conn.connected.is_set():
    time.sleep(1)
wss.authenticate()  #Success
###########################################################
myAcc = wss.wallets.get()

BTCw = myAcc[0][1][0][2]
USDw = myAcc[0][1][1][2]
print("Bitcoin bal is" ,BTCw)
print("USD bal is" ,USDw)
##################################################################
# Subscribe to some channels
wss.subscribe_to_ticker('BTCUSD')
wss.subscribe_to_order_book('BTCUSD')

#Accessing data stored in BtfxWss:
ticker_q=wss.tickers('BTCUSD')
while not ticker_q.empty():
    print(ticker_q.get())

#######################################
Morder = {           #Is the cid something randomly created by the user himself?
"cid":123456,
"type": "LIMIT",
"symbol": "tBTCUSD",
"amount": "0.01",
"price": 7499,
"hidden": 0
}
wss.new_order(**Morder)
while wss.orders.empty():
    time.sleep(1)
print(wss.orders.get())  ####return: (['os', []], 1511080754.160002)
#######################################
# Unsubscribing from channels:
wss.unsubscribe_from_ticker('BTCUSD')
wss.unsubscribe_from_order_book('BTCUSD')
wss.stop()
```

**Comment by nlsdfnbch** [comment]
hey @Michshelle !

Thanks for submitting this issue and contributing!

Regarding your issue:
```
[...]
while wss.orders.empty():
    time.sleep(1)
[...]
```
This won't do you much good, since the queue is generated in a ``defaultdict` for the current release, which will always return an empty object. Could you check and see if simply waiting a little longer resolves the issue ? It should only be a matter of timing, as I guess you simply call `get()` too early (ie the Client simply hasn't received the confirmation yet)

```python
[...]
Morder = {           #Is the cid something randomly created by the user himself?
"cid":123456,
"type": "LIMIT",
"symbol": "tBTCUSD",
"amount": "0.01",
"price": 7499,
"hidden": 0
}
wss.new_order(**Morder)
time.sleep(10)
print(wss.orders.get())  ####return: (['os', []], 1511080754.160002)
```

**Comment by Michshelle** [comment]
Thank you @nlsdfnbch for taking time on this.

Even it gets switched to the time.sleep(30), it still cannot work.
```
Morder = {
"cid": 245589,  #change to the API_Key Number
"type": "LIMIT",
"symbol": "tBTCUSD",
"amount": 0.01,
"price": 7499,
"hidden": 0
}

wss.new_order(**Morder)
time.sleep(30)
print(wss.orders.get())  ####Looks like an empty list
```  

FYI, If I created one order via browser, the orders.get() can return the details of the order.
`(['os', [[5273632715, None, 52387912113, 'tBTCUSD', 1511101987932, 1511101987973, 0.01, 0.01, 'EXCHANGE LIMIT', None, None, None, 0, 'ACTIVE', None, None, 7466, 0, None, None, None, None, None, 0, 0, 0]]], 1511102043.266698)`

BTW, I've added written permission to Orders, Wallets, Withdraw.

Regards,

Michelle

**Comment by Michshelle** [comment]
Hello @nlsdfnbch,

I'm able to order now.  No problem with your suggestion.  
The issue is with the type in Morder.  I should change it to EXCHANGE LIMIT to work, otherwise I got reminded  in the browser no enough balance to support the order (it may keep popping out there all the time, only I just noticed it).

One last question, is there a way I can print such error message to the log?   Trying to avoid silly questions in future...
Currently, the test log looks like,
```
INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'BTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'book', 'symbol': 'BTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('book', 'BTCUSD')
INFO:btfxwss.connection:Connection closed
```

Regards,

Michelle

**Comment by Michshelle** [comment]
Thank you!  I'm going to move the above question to a new issue.
